# This DeploymentRuntimeConfig will override the provider-sql deployment tolerations.
---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-sql
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              env:
                - name: DEBUG
                  value: "true"
                - name: CACHE_SYNC_TIMEOUT
                  value: "5m"
          tolerations:
            - effect: NoSchedule
              key: node.kubernetes.io/role
              operator: Equal
              value: crossplane
            - effect: NoSchedule
              key: node.kubernetes.io/arch
              operator: Equal
              value: arm64